eureka:
  client:
    registerWithEureka: true
    fetchRegistory: true
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
   web:
     exposure:
       include: hystrix.stream

hystix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000